#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app=‎WhatsApp manage=off
# Scratchpads
yabai -m rule --add app="^Spotify$" scratchpad=spotify grid=11:11:1:1:9:9
yabai -m rule --add app="^Messages$" scratchpad=messages grid=11:6:2:2:2:8
yabai -m rule --add app="^Microsoft Teams$" scratchpad=teams grid=11:11:1:1:9:9
yabai -m rule --add app="^Slack$" scratchpad=slack grid=11:11:1:1:9:9

# When an application is closed, just focus the next app that is under the cursor
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

# Fix ghostty
# HACK: very interesting issue here. Before, we were just setting layout to BSP unconditionally after ghostty tweaks. Now, we reset the space to whatever
# it was before, whether stack, bsp, or float
yabai -m signal --add app='^Ghostty$' event=window_created action='yabai -m space --layout $(yabai -m query --spaces --space | jq -r .type)'
yabai -m signal --add app='^Ghostty$' event=window_destroyed action='yabai -m space --layout $(yabai -m query --spaces --space | jq -r .type)'

yabai -m config \
                mouse_follows_focus off \
                focus_follows_mouse off \
                window_placement second_child \
                split_ratio 0.50 \
                split_type auto \
                auto_balance off \
                top_padding 10 \
                left_padding 10 \
                right_padding 10 \
                bottom_padding 10 \
                window_gap 10 \
                layout bsp \
                mouse_modifier fn \
                mouse_action1 move \
                mouse_action2 resize \
                mouse_drop_action swap

# Visual stuff
# yabai -m config \
#                 window_topmost off \
#                 window_shadow off \
#                 insert_feedback_color 0xaad75f5f \
#                 active_window_border_color 0xBF775759 \
#                 normal_window_border_color 0x7f353535 \
#                 window_border_width 4 \
#                 window_border_radius 12 \
#                 window_border_blur on \
#                 window_border_hidpi on \
#                 window_border on

echo "yabai configuration loaded.."
