#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Scratchpads
yabai -m rule --add app="^Spotify$" scratchpad=spotify grid=11:11:1:1:9:9
yabai -m rule --add app="^Messages$" scratchpad=messages grid=11:6:2:2:2:8
yabai -m rule --add app="^Microsoft Teams$" scratchpad=teams grid=11:11:1:1:9:9
yabai -m rule --add app="^Slack$" scratchpad=slack grid=11:11:1:1:9:9
yabai -m rule --add app=Discord scratchpad=discord grid=11:11:1:1:9:9

## Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app=‎WhatsApp manage=off

# When you close a focus window it finds the next window
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
yabai -m signal --add event=window_minimized active=yes action="if \$(yabai -m query --windows --window \$YABAI_WINDOW_ID | jq -r '.\"is-floating\"'); then yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null; fi"

yabai -m rule --add app='^Ghostty$' manage=off grid=1:1:0:0:1:1

yabai -m config \
                mouse_follows_focus off \
                focus_follows_mouse off \
                window_topmost on \
                window_animation_duration 0.0 \
                window_opacity_duration 0.0 \
                insert_feedback_color 0xffd75f5f \
                split_ratio 0.50 \
                split_type auto \
                auto_balance off \
                top_padding 12 \
                bottom_padding 12 \
                left_padding 12 \
                right_padding 12 \
                window_gap 12 \
                layout bsp \
                window_shadow float \
                mouse_modifier alt \
                mouse_action1 move \
                mouse_action2 resize \
                mouse_drop_action swap

# VERY IMPORTANT, this means existing windows inherit changes
yabai -m rule --apply

# When unplugging and plugging a monitor, this makes sure things size properly
yabai -m signal --add event=display_added action="yabai -m rule --apply"
yabai -m signal --add event=display_removed action="yabai -m rule --apply"

echo "yabai configuration loaded.."

# Make purple borders on active, nonthing on inactive
borders active_color=0xFFDC56FE inactive_color=0x0 width=7.0 &
echo "Borders activated..."
